### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by himenekocn** [rockCityMath/CS2-Multi-1v1#1]
16:24:17 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.CBaseEntity.get_CBodyComponent() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 4369
   at CounterStrikeSharp.API.Core.CBaseEntity.get_AbsOrigin() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBaseEntity.cs:line 23
   at CS2Multi1v1.Models.Arena.OnPlayerSpawn(CCSPlayerController playerController)
   at CS2Multi1v1.CS2Multi1v1.OnPlayerSpawn(EventPlayerSpawn event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by rockCityMath** [comment]
Please provide exact recreation steps if this is still an issue.
